id: IF789877A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T21:44:19+00:00'
last_modified: '2022-06-07T15:11:09.630607+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18685
  title: ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་ཁྲིམས་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    B9A6:
      image_group_id: I8LS18687
      title: ''
      total_pages: 1025
      order: 1
      base_file: B9A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
