id: P001794
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18685
  title: ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་ཁྲིམས་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    a6f3d8a98bf24e15b3ce33a0c68677b9:
      image_group_id: I8LS18687
      title: ''
      volume_number: 1
      total_pages: 1025
      base_file: v001.txt
